### ISSUE TITLE
Blockchain Integration?

### ISSUE THREAD

**Issue by vathzen** [delta/auction_system#1]
Use A Lightweight Blockchain backend like Hyperledger Iroha to spice things up? Added benefits include increased security and inbuild encryption.

**Comment by adarshPatel509** [comment]
Hey @froossv!, we are building a real time system for which speed is the most important aspect. We really don't need to use any blockchain technology as we are not dealing with as such sensitive data. And in blockchain, making a transaction itself will take significant amount of time.
Using node and sockets itself we can assure primary security & encryption. 

And for any quires you can always ask to our slack channel https://join.slack.com/t/dwocauctionsystem/shared_invite/enQtODA3NTcwMjU0MDIxLThlZWNkNTAwMDZlMTAwMWI1OTc3N2I0YTE0MmY3NmRjNDg5OWE3MzI5MTc3YTU3YjRlMmRiZWU4NGZhMzgyOTk 
Thanks!
